
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author OM NAIK
 */
public class Dash2 extends javax.swing.JFrame {

    Connection connect = null;

    /**
     * Creates new form Dash2
     */
    public Dash2() {
        initComponents();
        connect = SQLClass.dbConnector();
    }

    public Dash2(String uname) {
        initComponents();
        connect = SQLClass.dbConnector();
        //String sql = "SELECT * FROM customer";
        update(uname);
    }

    public void update(String uname) {
        try {

            String sql = "SELECT * FROM customer WHERE Username = '" + uname + "'";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Address");
                address.setText(add1);
                String add2 = rs.getString("Name");
                name.setText(add2);
                String add3 = rs.getString("Mobile");
                mobile.setText(add3);
                String add4 = rs.getString("Email");
                email.setText(add4);
                //String add5 = rs.getString("Customer");
                username.setText(uname);
                jPanel3.repaint();
                String uid1 = rs.getString("CID");
                uid.setText(uid1);
                rs.close();
                pst.close();

            }

        } catch (Exception e) {
            System.out.print(e);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperStorage.com");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 0));
        jTabbedPane1.setAlignmentX(0.0F);
        jTabbedPane1.setAlignmentY(0.0F);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(850, 510));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(850, 510));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 510));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 100, 70, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username: ");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 140, 80, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email ID :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 180, 70, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address : ");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 260, 70, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 220, 60, 25);

        username.setEditable(false);
        jPanel3.add(username);
        username.setBounds(120, 140, 240, 25);

        name.setEditable(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel3.add(name);
        name.setBounds(120, 100, 240, 25);

        address.setEditable(false);
        jPanel3.add(address);
        address.setBounds(120, 260, 240, 25);

        mobile.setEditable(false);
        jPanel3.add(mobile);
        mobile.setBounds(120, 220, 240, 25);

        email.setEditable(false);
        jPanel3.add(email);
        email.setBounds(120, 180, 240, 25);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(220, 180, 71, 21);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 60, 70, 25);

        uid.setEditable(false);
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        jPanel3.add(uid);
        uid.setBounds(120, 60, 240, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("User Details");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(0, 0, 400, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 80, 780, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OM NAIK\\Desktop\\Superstorage1.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 180, 80);

        jTabbedPane1.addTab("Profile", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.setMinimumSize(new java.awt.Dimension(850, 510));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Netbeans\\Projects\\dbmsproject\\src\\main\\java\\weofferhome-1.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 110, 360, 370);

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Netbeans\\Projects\\dbmsproject\\src\\main\\java\\weofferhome-2.png")); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(450, 130, 360, 310);

        jPanel6.setBackground(new java.awt.Color(255, 102, 0));
        jPanel6.setLayout(null);

        jLabel25.setBackground(new java.awt.Color(255, 102, 0));
        jLabel25.setFont(new java.awt.Font("Basketball", 0, 28)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Storage Units");
        jLabel25.setToolTipText("");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(180, 180, 146, 28);

        jLabel23.setBackground(new java.awt.Color(255, 102, 0));
        jLabel23.setFont(new java.awt.Font("Basketball", 0, 28)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Storage Boxes");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(410, 170, 360, 40);

        jLabel24.setBackground(new java.awt.Color(255, 102, 0));
        jLabel24.setFont(new java.awt.Font("Basketball", 0, 48)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Storage Units");
        jLabel24.setToolTipText("");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(50, 20, 340, 80);

        jLabel22.setBackground(new java.awt.Color(255, 102, 0));
        jLabel22.setFont(new java.awt.Font("Basketball", 0, 48)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Storage Boxes");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(500, 20, 262, 80);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 840, 110);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Book Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(660, 450, 160, 40);

        jTabbedPane1.addTab("Services", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));
        jPanel5.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("<html>B/303,<br>Pranav Estate,<br>M. K. Road,<br>Sewri (W),<br>Mumbai - 400234.");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(130, 160, 120, 120);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<html>98631 XXXXX<br>98452 XXXXX");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(130, 280, 100, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Head Office:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(30, 160, 90, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("sales@superstorage.com");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(130, 330, 180, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Call us at: ");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 280, 80, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Mon - Sat: 10:00 - 19:00");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(130, 360, 180, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 330, 80, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Time:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(30, 360, 80, 30);

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\OM NAIK\\Downloads\\Superstorage.png")); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 10, 260, 100);

        jPanel5.add(jPanel4);
        jPanel4.setBounds(0, 0, 840, 120);

        jTabbedPane1.addTab("Contact us", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 850, 550);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Profile");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void action_start() {
        String sql = "SELECT * FROM customer WHERE CID = (?)";
        PreparedStatement pst;
        try {
            pst = connect.prepareStatement(sql);

        } catch (Exception e) {
            System.out.print(e);
        }
    }
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Service_Details sd = new Service_Details(uid.getText());
        sd.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
                                     
        Serv_Det sd1 = new Serv_Det();
        sd1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String uid1 = uid.getText();
        Booking_Window bw = new Booking_Window(uid1);
        bw.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dash2().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField uid;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
