/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Parth
 */
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class firstpage extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    /**
     * Creates new form firstpage
     */
    public firstpage() {
        initComponents();
        conn = SQLClass.dbConnector();
        CurrentDate();
        Update();
    }
    public firstpage(String pare) {
        initComponents();
        conn = SQLClass.dbConnector();
        CurrentDate();
        Update();
        jLabel3.setText(pare);
    }
    public void Update(){
        try{
            String sql = "SELECT Name, Username, Address, Email, Mobile FROM customer";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }
    public void CurrentDate(){
        Thread clock = new Thread(){
            public void run(){
                for(;;){
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    jMenu4.setText("Date " +day+"-"+(month+1)+"-"+year );
    
    int hour=cal.get(Calendar.HOUR);
    int min=cal.get(Calendar.MINUTE);
    int sec=cal.get(Calendar.SECOND);
    jMenu5.setText("Time " +hour+":"+(min)+":"+sec);
    
    try{
        sleep(1000);
    }catch(InterruptedException ex){
        Logger.getLogger(firstpage.class.getName()).log(Level.SEVERE,null, ex);
    }
                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cust_table = new javax.swing.JTable();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        Name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobile_no = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(840, 520));
        getContentPane().setLayout(null);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 430, 31, 13);

        cust_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        cust_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cust_table);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 70, 450, 250);

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(0, 0, 153));
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updatebutton);
        updatebutton.setBounds(510, 350, 120, 30);

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 0, 0));
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton);
        deletebutton.setBounds(340, 350, 120, 30);

        clearbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 102, 0));
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clearbutton);
        clearbutton.setBounds(670, 350, 120, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 350, 120, 30);

        savebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton);
        savebutton.setBounds(20, 350, 120, 30);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(620, 20, 166, 31);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 120, 94, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 240, 94, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mobile No:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 290, 94, 26);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Search:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 20, 94, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 170, 94, 25);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(620, 170, 166, 50);
        getContentPane().add(Name);
        Name.setBounds(620, 120, 166, 31);
        getContentPane().add(email);
        email.setBounds(620, 240, 166, 31);
        getContentPane().add(mobile_no);
        mobile_no.setBounds(620, 290, 166, 31);

        username.setEditable(false);
        getContentPane().add(username);
        username.setBounds(620, 70, 166, 31);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Username:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(510, 70, 94, 28);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Date");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Time");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        try{
           String sql = "INSERT INTO customer(Name,Username,Address,Email,Mobile)values(?,?,?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1, Name.getText());
           pst.setString(2, username.getText());
           pst.setString(3, address.getText());
           pst.setString(4, email.getText());
           pst.setString(5, mobile_no.getText());
           
     
//           
           pst.execute();
           JOptionPane.showMessageDialog(null,"Data saved");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }Update();
    }//GEN-LAST:event_savebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null,"Are you sure","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            String sql="delete from Customer where FirstName=?";
            try{
                pst=conn.prepareStatement(sql);
                pst.setString(1,Name.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "deleted");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }Update();
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        try{
            String val1 = Name.getText();
            String val3 = address.getText();
            String val4 = email.getText();
            String val5 = mobile_no.getText();
            String val6 = username.getText();
            
            String sql = "UPDATE customer SET Name='"+val1+"',Address='"+val3+"',Email='"+val4+"',Mobile='"+val5+"',Username='"+val6+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data updated");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        Name.setText("");
    
        address.setText("");
        email.setText("");
        mobile_no.setText("");
        username.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try{
           String sql = "SELECT * FROM customer WHERE username = ?";
           pst=conn.prepareStatement(sql);
           pst.setString(1, search.getText());
           rs=pst.executeQuery();
          // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           if (rs.next()) {
                String add1 = rs.getString("Name");
                Name.setText(add1);
                String add2 = rs.getString("Username");
                username.setText(add2);
                String add3 = rs.getString("Address");
                address.setText(add3);
                String add4 = rs.getString("Email");
                email.setText(add4);
                String add5 = rs.getString("Mobile");
                mobile_no.setText(add5);
                           }
            cust_table.setModel(DbUtils.resultSetToTableModel(rs));
         pst.close();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
           String sql = "SELECT * FROM customer";
           PreparedStatement pst = conn.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();
           cust_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cust_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_tableMouseClicked
        try {
            int row = cust_table.getSelectedRow();
            String table_click = (cust_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM customer WHERE CID = '" + table_click + "' ";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Name");
                Name.setText(add1);
                String add2 = rs.getString("Username");
                username.setText(add2);
                String add3 = rs.getString("Address");
                address.setText(add3);
                String add4 = rs.getString("Email");
                email.setText(add4);
                String add5 = rs.getString("Mobile");
                mobile_no.setText(add5);
                rs.close();
                pst.close();
                           }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cust_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextArea address;
    private javax.swing.JButton clearbutton;
    private javax.swing.JTable cust_table;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField mobile_no;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField search;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
