/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author OM NAIK
 */
public class Units extends javax.swing.JFrame {

    /**
     * Creates new form Units
     */
    Connection connect = null;

    public Units() {
        initComponents();
        connect = SQLClass.dbConnector();

    }
public Units(String usern) {
        initComponents();
        connect = SQLClass.dbConnector();
        username2.setText(usern);
    }
    public void Update() {
        
        try {
            String sql = "SELECT Name, Username, Address, Email, Mobile FROM customer";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            pst = connect.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unitNo = new javax.swing.JTextField();
        Section = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        unit_table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        TDateP = new com.toedter.calendar.JDateChooser();
        FDateP = new com.toedter.calendar.JDateChooser();
        StatusC = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cust_table = new javax.swing.JTable();
        updatebutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        Name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobile_no = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        username2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperStorage.com");
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(850, 510));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Load");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 440, 120, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 440, 120, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 440, 120, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(570, 440, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Type:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 290, 70, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Section:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 170, 70, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Unit No.:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 130, 70, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Status:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 250, 70, 25);

        unitNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(unitNo);
        unitNo.setBounds(620, 130, 150, 30);

        Section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Section);
        Section.setBounds(620, 170, 150, 30);

        Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        jPanel1.add(Type);
        Type.setBounds(620, 290, 150, 30);

        Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusActionPerformed(evt);
            }
        });
        jPanel1.add(Status);
        Status.setBounds(620, 90, 150, 30);

        unit_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        unit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        unit_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unit_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(unit_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 452, 300);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("From:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 330, 70, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("CID:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 210, 70, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Till:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 370, 70, 25);

        custName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(custName);
        custName.setBounds(620, 210, 150, 30);

        TDateP.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(TDateP);
        TDateP.setBounds(620, 370, 170, 30);

        FDateP.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(FDateP);
        FDateP.setBounds(620, 330, 170, 30);

        StatusC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacant", "Occupied" }));
        jPanel1.add(StatusC);
        StatusC.setBounds(620, 250, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OM NAIK\\Desktop\\Superstorage1.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 180, 100);

        jTabbedPane1.addTab("Units", jPanel1);

        jPanel2.setLayout(null);

        cust_table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cust_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        cust_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cust_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(cust_table);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(30, 100, 450, 300);

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(0, 0, 153));
        updatebutton.setText("Update");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(updatebutton);
        updatebutton.setBounds(460, 430, 120, 30);

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(255, 0, 0));
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(deletebutton);
        deletebutton.setBounds(240, 430, 120, 30);

        clearbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbutton.setForeground(new java.awt.Color(255, 102, 0));
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(clearbutton);
        clearbutton.setBounds(680, 430, 120, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 0));
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(30, 430, 120, 30);

        savebutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(savebutton);
        savebutton.setBounds(50, 350, 120, 30);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search);
        search.setBounds(630, 110, 166, 31);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(520, 190, 94, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Email:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(520, 330, 94, 31);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Mobile No:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(520, 370, 94, 26);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Search:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(520, 110, 94, 28);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Address:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(520, 270, 94, 25);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(630, 270, 166, 50);
        jPanel2.add(Name);
        Name.setBounds(630, 230, 166, 31);
        jPanel2.add(email);
        email.setBounds(630, 330, 166, 31);
        jPanel2.add(mobile_no);
        mobile_no.setBounds(630, 370, 166, 31);

        username.setEditable(false);
        jPanel2.add(username);
        username.setBounds(630, 150, 166, 31);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Username:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(520, 150, 94, 28);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\OM NAIK\\Desktop\\Superstorage1.png")); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 0, 180, 100);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Name:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(520, 230, 94, 25);

        username1.setEditable(false);
        jPanel2.add(username1);
        username1.setBounds(630, 190, 166, 31);

        username2.setText("jLabel17");
        jPanel2.add(username2);
        username2.setBounds(390, 150, 36, 13);

        jTabbedPane1.addTab("Customers", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 850, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String query = "SELECT * FROM unitsA";
            PreparedStatement pst = connect.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            unit_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void unit_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unit_tableMouseClicked
        try {
            int row = unit_table.getSelectedRow();
            String table_click = (unit_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM unitsA WHERE ID = '" + table_click + "' ";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("ID");
                unitNo.setText(add1);
                String add2 = rs.getString("Section");
                Section.setText(add2);
                String add3 = rs.getString("Type");
                Type.setText(add3);
                String add4 = rs.getString("Status");
                Status.setText(add4);
                String add5 = rs.getString("CID");
                custName.setText(add5);
                String add6 = rs.getString("From");
                System.out.println(add6);
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(add6);
                FDateP.setDate(date);
                String add7 = rs.getString("Till");
                java.util.Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(add7);
                TDateP.setDate(date1);
                rs.close();
                pst.close();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_unit_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sql = "INSERT INTO unitsA VALUES (?,?,?,?,?,?,?)";
        PreparedStatement pst;
        try {
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            pst = connect.prepareStatement(sql);

            pst.setString(1, unitNo.getText());
            pst.setString(3, Section.getText());
            pst.setString(2, custName.getText());
            String stat = StatusC.getSelectedItem().toString();
            pst.setString(4, stat);
            pst.setString(5, Type.getText());
            
            pst.setString(6, df.format(FDateP.getDate()));
            pst.setString(7, df.format(TDateP.getDate()));
            /*if ((stat == "Occupied") && (custName.getText() == null) && (df.format(FDateP.getDate()) == null) && (df.format(TDateP.getDate()) == null)) {
                JOptionPane.showMessageDialog(null, "Data Error");
            } else {
                pst.execute();
            }*/
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data saved");
            pst.close();

        } catch (Exception e) {
            System.out.print(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String sql = "DELETE FROM unitsA WHERE ID = '" + unitNo.getText() + "'";
            PreparedStatement pst = connect.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Deleted");
            pst.close();
        } catch (Exception e) {
            System.out.print(e);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        unitNo.setText(null);
        Section.setText(null);
        custName.setText(null);
        Status.setText(null);
        Type.setText(null);
        FDateP.setDate(null);
        TDateP.setDate(null);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusActionPerformed

    private void cust_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cust_tableMouseClicked
        try {
            int row = cust_table.getSelectedRow();
            String table_click = (cust_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM customer WHERE CID = '" + table_click + "' ";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Name");
                Name.setText(add1);
                String add2 = rs.getString("Username");
                username.setText(add2);
                String add3 = rs.getString("Address");
                address.setText(add3);
                String add4 = rs.getString("Email");
                email.setText(add4);
                String add5 = rs.getString("Mobile");
                mobile_no.setText(add5);
                String add6 = rs.getString("CID");
                username1.setText(add6);
                rs.close();
                pst.close();
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cust_tableMouseClicked

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        try {
            String val1 = Name.getText();
            String val3 = address.getText();
            String val4 = email.getText();
            String val5 = mobile_no.getText();
            String val6 = username.getText();

            String sql = "UPDATE customer SET Name='" + val1 + "',Address='" + val3 + "',Email='" + val4 + "',Mobile='" + val5 + "',Username='" + val6 + "'";
            PreparedStatement pst = connect.prepareStatement(sql);
            pst = connect.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            String sql = "DELETE FROM customer WHERE CID = ?";
            try {
                PreparedStatement pst = connect.prepareStatement(sql);
                pst = connect.prepareStatement(sql);
                pst.setString(1, username1.getText());
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(null, "deleted");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        Update();
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        username1.setText("");
        address.setText("");
        email.setText("");
        mobile_no.setText("");
        username.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM customer";
            PreparedStatement pst = connect.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            cust_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO customer(Name,Username,Address,Email,Mobile)values(?,?,?,?,?)";
            PreparedStatement pst = connect.prepareStatement(sql);
            pst = connect.prepareStatement(sql);
            pst.setString(1, Name.getText());
            pst.setString(2, username.getText());
            pst.setString(3, address.getText());
            pst.setString(4, email.getText());
            pst.setString(5, mobile_no.getText());

            //
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        Update();
    }//GEN-LAST:event_savebuttonActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM customer WHERE username = ?";
            PreparedStatement pst = connect.prepareStatement(sql);

            pst = connect.prepareStatement(sql);
            pst.setString(1, search.getText());

            ResultSet rs = pst.executeQuery();
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if (rs.next()) {
                String add1 = rs.getString("Name");
                Name.setText(add1);
                String add2 = rs.getString("Username");
                username.setText(add2);
                String addID = rs.getString("CID");
                username1.setText(addID);
                String add3 = rs.getString("Address");
                address.setText(add3);
                String add4 = rs.getString("Email");
                email.setText(add4);
                String add5 = rs.getString("Mobile");
                mobile_no.setText(add5);
            }
            cust_table.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Units.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Units.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Units.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Units.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Units().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FDateP;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Section;
    private javax.swing.JTextField Status;
    private javax.swing.JComboBox<String> StatusC;
    private com.toedter.calendar.JDateChooser TDateP;
    private javax.swing.JTextField Type;
    private javax.swing.JTextArea address;
    private javax.swing.JButton clearbutton;
    private javax.swing.JTextField custName;
    private javax.swing.JTable cust_table;
    private javax.swing.JButton deletebutton;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mobile_no;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField search;
    private javax.swing.JTextField unitNo;
    private javax.swing.JTable unit_table;
    private javax.swing.JButton updatebutton;
    private javax.swing.JTextField username;
    private javax.swing.JTextField username1;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables
}
